version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: retail
      MYSQL_USER: retail
      MYSQL_PASSWORD: retail
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mysql

volumes:
  mysql_data: